### ISSUE TITLE
请教作者，有交流的群吗？服务端代码是付费的吗？

### ISSUE THREAD

**Issue by coreuml** [developerHUA/china_push#1]
请教作者，有交流的群吗？服务端代码是付费的吗？

**Comment by developerHUA** [comment]
服务端就是调用各个厂商的推送接口，给设备发送消息。我用的Java写的，需要的话可以发你一份

**Comment by developerHUA** [comment]
> 请教作者，有交流的群吗？服务端代码是付费的吗？

服务端就是调用各个厂商的推送接口，给设备发送消息。我用的Java写的，需要的话可以发你一份

**Comment by coreuml** [comment]
> > 请教作者，有交流的群吗？服务端代码是付费的吗？
> 
> 服务端就是调用各个厂商的推送接口，给设备发送消息。我用的Java写的，需要的话可以发你一份

我是新手，需要这个，我如何联系您？我的邮箱：24723422@qq.com

**Comment by shadowyy** [comment]
服务端代码可以开源下么
